remote_theme: clzirbel/github-pages-theme
title: PVA Photo and Video Annotator
description: Photo and video annotation tool
markdown: kramdown
keywords:
  - video annotation
  - photo annotation
  - research tools
  - desktop application